# Creates a backup of player progress in Minecraft and Infinity
# Please only edit this if you know what you're doing
#
# Available options: seconds, minutes, hours
#
# Example:
# player-data-backup-interval: 10.5 - This saves the player progress in both game modes every ten minutes
#
# To save every few seconds for example, set the number to .3
# To save every few minutes for example, set the number to .5
# To save every few hours for example, set to number to .8
player-data-backup-interval: 10.5